[project]
name = "merlin-voice-control-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sounddevice>=0.5.4",
    "vosk>=0.3.45",
]
